### ISSUE TITLE
Installing with Nox doesn’t work on non-NixOS

### ISSUE THREAD

**Issue by kirelagin** [madjar/nox#17]
I’m using Nix on my Gentoo laptop. When I try to install anything with Nox here is what I get:

~~~~
Packages to install: 1
installing ‘gimp-2.8.14’
error: couldn't change to directory of ‘/nix/var/nix/daemon-socket/socket’: No such file or directory
(use ‘--show-trace’ to show detailed location information)
Traceback (most recent call last):
  File "/nix/store/7z216gzdvyba3l2nslay345ck1wbnkph-nox-0.0.1/bin/..nox-wrapped-wrapped", line 11, in <module>
    sys.exit(main())
  File "/nix/store/sa0zc1pbqz31cn1v1rsimyc3ac0vffz9-python3.4-click-2.1/lib/python3.4/site-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/sa0zc1pbqz31cn1v1rsimyc3ac0vffz9-python3.4-click-2.1/lib/python3.4/site-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/nix/store/sa0zc1pbqz31cn1v1rsimyc3ac0vffz9-python3.4-click-2.1/lib/python3.4/site-packages/click/core.py", line 653, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/sa0zc1pbqz31cn1v1rsimyc3ac0vffz9-python3.4-click-2.1/lib/python3.4/site-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/7z216gzdvyba3l2nslay345ck1wbnkph-nox-0.0.1/lib/python3.4/site-packages/nox/search.py", line 73, in main
    subprocess.check_call(['nix-env', '-iA'] + attributes)
  File "/nix/store/904bkwbqs9p9dxx07v7b2p0f1cqq7lif-python3-3.4.2/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nix-env', '-iA', 'nixpkgs.gimp']' returned non-zero exit status 1
~~~~

The problem is that `nix-env` is looking for the daemon socket at `/nix/var/nix/daemon-socket/`, but it’s not there, it’s in `/var/lib/nix/daemon-socket/`. This happens because Nox itself is wrapped in such a way that it calls `nix-env` from the nix store instead of calling the system one and it seems like some magic in Nix build system makes it store its state in different places in NixOS and Gentoo (note that the Gentoo ebuild doesn’t override any default paths).

I couldn’t figure out exactly what magic makes Nix use different paths for its state, but the point is `nix-env` invocation by Nox should be exactly equivalent to typing in the terminal, so it shouldn’t be wrapped because it should call system `nix-env`.

**Comment by kirelagin** [comment]
P.S. This is actually a bug in nixpkgs, not Nox, but I thought here might be a more appropriate place to report it.

**Comment by madjar** [comment]
Thanks a lot for the investigation and the fix :)
