### ISSUE TITLE
Running `nox-update` on a debian with nix fails

### ISSUE THREAD

**Issue by matthiasbeyer** [madjar/nox#18]
All I know is:

```bash
$ nox-update 
Traceback (most recent call last):
  File "/nix/store/42fk57bs6icl5lgv836n49lz1hpcsz7i-nox-0.0.1/bin/.nox-update-wrapped", line 11, in <module>
    sys.exit(main())
  File "/nix/store/8wy20r2ca9i5nmmc08r2zsyhigj2hych-python3.4-click-2.1/lib/python3.4/site-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/8wy20r2ca9i5nmmc08r2zsyhigj2hych-python3.4-click-2.1/lib/python3.4/site-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/nix/store/8wy20r2ca9i5nmmc08r2zsyhigj2hych-python3.4-click-2.1/lib/python3.4/site-packages/click/core.py", line 653, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/8wy20r2ca9i5nmmc08r2zsyhigj2hych-python3.4-click-2.1/lib/python3.4/site-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/42fk57bs6icl5lgv836n49lz1hpcsz7i-nox-0.0.1/lib/python3.4/site-packages/nox/update.py", line 93, in main
    new_drv = new_system_drv()
  File "/nix/store/42fk57bs6icl5lgv836n49lz1hpcsz7i-nox-0.0.1/lib/python3.4/site-packages/nox/update.py", line 60, in new_system_drv
    universal_newlines=True) as process:
  File "/nix/store/ygvzpxyn1cyw90yhj39c643bvm2wpcqh-python3-3.4.2/lib/python3.4/subprocess.py", line 858, in __init__
    restore_signals, start_new_session)
  File "/nix/store/ygvzpxyn1cyw90yhj39c643bvm2wpcqh-python3-3.4.2/lib/python3.4/subprocess.py", line 1456, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'nixos-rebuild'

```

Ask me for more information if you need more...

**Comment by madjar** [comment]
That's mainly a documentation fail on my part. Nixos-update is an experimental command that tells you why stuff are rebuilt when you upgrade the system (ie when you run nixos-rebuild). Obviously, this fails on debian.

Still, a nicer error message would be nice.

**Comment by matthiasbeyer** [comment]
So I guess this is a feature request for a better error message from now on! :smile:

**Comment by davidak** [comment]
same error on darwin. i expected that it tells me what packages i can update (installed with nix)

```
$ nox-update
Traceback (most recent call last):
  File "/nix/store/5jc88y1kfkymgg469kdy1d934dnjls1m-nox-0.0.2/bin/.nox-update-wrapped", line 11, in <module>
    sys.exit(main())
  File "/nix/store/1hxjlkv0ip5x3qxh1f6cpvrbfvx80ifw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/1hxjlkv0ip5x3qxh1f6cpvrbfvx80ifw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/nix/store/1hxjlkv0ip5x3qxh1f6cpvrbfvx80ifw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/1hxjlkv0ip5x3qxh1f6cpvrbfvx80ifw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/5jc88y1kfkymgg469kdy1d934dnjls1m-nox-0.0.2/lib/python3.4/site-packages/nox/update.py", line 93, in main
    new_drv = new_system_drv()
  File "/nix/store/5jc88y1kfkymgg469kdy1d934dnjls1m-nox-0.0.2/lib/python3.4/site-packages/nox/update.py", line 60, in new_system_drv
    universal_newlines=True) as process:
  File "/nix/store/lwq4k9vh197mrbgzcvrd6y25yvzp3vcd-python3-3.4.3/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/nix/store/lwq4k9vh197mrbgzcvrd6y25yvzp3vcd-python3-3.4.3/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'nixos-rebuild'
```

So the second part of this feature request is compatibility with just stand-alone Nix.
