### ISSUE TITLE
Permission denied when running nox as as a different user

### ISSUE THREAD

**Issue by aragnon** [madjar/nox#30]
`nox ihaskell` 

```
Warning: could not find a version indicator for /home/sharednix/.nix-defexpr/nixpkgs
Traceback (most recent call last):
  File "/nix/store/33pg4ryh11x02gikp0a5ivw2zshjd30h-nox-0.0.2/bin/.nox-wrapped", line 11, in <module>
    sys.exit(main())
  File "/nix/store/ljji9lp3iq57p1a1bj40iv1n3ilrsmxw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/ljji9lp3iq57p1a1bj40iv1n3ilrsmxw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/nix/store/ljji9lp3iq57p1a1bj40iv1n3ilrsmxw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/ljji9lp3iq57p1a1bj40iv1n3ilrsmxw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/33pg4ryh11x02gikp0a5ivw2zshjd30h-nox-0.0.2/lib/python3.4/site-packages/nox/search.py", line 56, in main
    results = [p for p in all_packages()
  File "/nix/store/33pg4ryh11x02gikp0a5ivw2zshjd30h-nox-0.0.2/lib/python3.4/site-packages/nox/search.py", line 46, in all_packages
    packages_json = region.get_or_create(key, nix_packages_json)
  File "/nix/store/pm27izhmg0il3752hw0z1bmvzn97gnkn-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/region.py", line 640, in get_or_create
    async_creator) as value:
  File "/nix/store/aihxp914s3d5f5gammpxwicn8rqz3plh-python3.4-dogpile.core-0.4.1/lib/python3.4/site-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/nix/store/aihxp914s3d5f5gammpxwicn8rqz3plh-python3.4-dogpile.core-0.4.1/lib/python3.4/site-packages/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/nix/store/aihxp914s3d5f5gammpxwicn8rqz3plh-python3.4-dogpile.core-0.4.1/lib/python3.4/site-packages/dogpile/core/dogpile.py", line 128, in _enter_create
    self.mutex.acquire()
  File "/nix/store/pm27izhmg0il3752hw0z1bmvzn97gnkn-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/util.py", line 172, in acquire
    elif self.mutex.acquire(wait=wait):
  File "/nix/store/pm27izhmg0il3752hw0z1bmvzn97gnkn-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/backends/file.py", line 303, in acquire
    return self.acquire_write_lock(wait)
  File "/nix/store/pm27izhmg0il3752hw0z1bmvzn97gnkn-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/backends/file.py", line 405, in acquire_write_lock
    return self._acquire(wait, os.O_WRONLY, self._module.LOCK_EX)
  File "/nix/store/pm27izhmg0il3752hw0z1bmvzn97gnkn-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/backends/file.py", line 415, in _acquire
    fileno = os.open(self.filename, wrflag)
PermissionError: [Errno 13] Permission denied: '/tmp/nox.dbm.dogpile.lock'
```

The file `/tmp/nox.dbm.dogpile.lock` is already owned by some unrelated user johndoe, which seems to give the impression that nox is not a multi-user program.

**Comment by madjar** [comment]
Let's say it's not as much not multi-user as not multi-user-tested :)

Thanks for the report, I'll look into it!

**Comment by bzizou** [comment]
I suggest the following patch:
```
diff --git a/nox/cache.py b/nox/cache.py                      
index 169f626..f3c29b3 100644                                 
--- a/nox/cache.py                                            
+++ b/nox/cache.py                                            
@@ -1,7 +1,8 @@                                               
 from dogpile.cache import make_region                        
+import getpass                                               
                                                              
 region = make_region().configure(                            
     'dogpile.cache.dbm',                                     
     expiration_time=3600,                                    
-    arguments={'filename': '/tmp/nox.dbm'}                   
+    arguments={'filename': '/tmp/nox.dbm.'+getpass.getuser()}
 )                                                            
```
