### ISSUE TITLE
Merging PR into base failed

### ISSUE THREAD

**Issue by davidak** [madjar/nox#35]
```
$ nox-review pr 12319
=== Reviewing PR 12319 : xkcdpass: init at 1.4.2
==> Fetching base (master)
==> Fetching PR
==> Fetching extra history for merging
==> Merging PR into base
Auto-merging pkgs/development/haskell-modules/hackage-packages.nix
CONFLICT (content): Merge conflict in pkgs/development/haskell-modules/hackage-packages.nix
Auto-merging pkgs/development/haskell-modules/configuration-lts-4.1.nix
CONFLICT (add/add): Merge conflict in pkgs/development/haskell-modules/configuration-lts-4.1.nix
Auto-merging pkgs/development/haskell-modules/configuration-lts-3.22.nix
CONFLICT (add/add): Merge conflict in pkgs/development/haskell-modules/configuration-lts-3.22.nix
Auto-merging pkgs/development/haskell-modules/configuration-ghc-7.10.x.nix
Auto-merging pkgs/data/misc/geolite-legacy/default.nix
CONFLICT (content): Merge conflict in pkgs/data/misc/geolite-legacy/default.nix
Auto-merging nixos/modules/security/acme.nix
CONFLICT (content): Merge conflict in nixos/modules/security/acme.nix
Automatic merge failed; fix conflicts and then commit the result.
Traceback (most recent call last):
  File "/nix/store/5jc88y1kfkymgg469kdy1d934dnjls1m-nox-0.0.2/bin/.nox-review-wrapped", line 11, in <module>
    sys.exit(cli())
  File "/nix/store/1hxjlkv0ip5x3qxh1f6cpvrbfvx80ifw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/1hxjlkv0ip5x3qxh1f6cpvrbfvx80ifw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/nix/store/1hxjlkv0ip5x3qxh1f6cpvrbfvx80ifw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/1hxjlkv0ip5x3qxh1f6cpvrbfvx80ifw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/1hxjlkv0ip5x3qxh1f6cpvrbfvx80ifw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/1hxjlkv0ip5x3qxh1f6cpvrbfvx80ifw-python3.4-click-5.1/lib/python3.4/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/5jc88y1kfkymgg469kdy1d934dnjls1m-nox-0.0.2/lib/python3.4/site-packages/nox/review.py", line 124, in review_pr
    repo.git(['merge', head, '-qm', 'Nox automatic merge'])
  File "/nix/store/5jc88y1kfkymgg469kdy1d934dnjls1m-nox-0.0.2/lib/python3.4/site-packages/nox/nixpkgs_repo.py", line 48, in git
    return f(command, *args, cwd=cwd, universal_newlines=output, **kwargs)
  File "/nix/store/lwq4k9vh197mrbgzcvrd6y25yvzp3vcd-python3-3.4.3/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'merge', 'cf184179bd83f3bc3f22ebf0c46832a3a8930478', '-qm', 'Nox automatic merge']' returned non-zero exit status 1
```

**Comment by madjar** [comment]
Damned. That was not suppose to happen any more :(

When nox clones the nixpkgs repository, it does a shallow clone to avoid downloading the whole history (which is pretty big by now). I though I was downloading enough history to merge troubles, but that doesn't seem to be the case.

Could you run `cd ~/.nox/nixpkgs; git fetch`, try again, and tell me if it works?

**Comment by davidak** [comment]
yes, no, same error.

i have nox-0.0.2 but that seams to be the latest version.

```
$ cd ~/.nox/nixpkgs; git fetch
remote: Counting objects: 609501, done.
remote: Compressing objects: 100% (157172/157172), done.
remote: Total 609501 (delta 413212), reused 605278 (delta 409298), pack-reused 0
Receiving objects: 100% (609501/609501), 257.79 MiB | 982.00 KiB/s, done.
Resolving deltas: 100% (413212/413212), completed with 2731 local objects.
From https://github.com/NixOS/nixpkgs
[...]
$ nox-review pr 12319
=== Reviewing PR 12319 : xkcdpass: init at 1.4.2
==> Old version of git detected (git version 1.9.5 (Apple Git-50.3), maybe on travis), not trying to fetch from local, fetch 50 commits from master instead
remote: Counting objects: 3480, done.
remote: Compressing objects: 100% (1996/1996), done.
remote: Total 3480 (delta 2539), reused 2301 (delta 1460), pack-reused 0
Receiving objects: 100% (3480/3480), 1.84 MiB | 1.06 MiB/s, done.
Resolving deltas: 100% (2539/2539), completed with 248 local objects.
From https://github.com/NixOS/nixpkgs
 * branch            master     -> FETCH_HEAD
==> Fetching base (master)
==> Fetching PR
==> Fetching extra history for merging
==> Merging PR into base
nixos/modules/security/acme.nix: needs merge
pkgs/data/misc/geolite-legacy/default.nix: needs merge
pkgs/development/haskell-modules/configuration-lts-3.22.nix: needs merge
pkgs/development/haskell-modules/configuration-lts-4.1.nix: needs merge
pkgs/development/haskell-modules/hackage-packages.nix: needs merge
error: you need to resolve your current index first
Traceback (most recent call last):
  File "/nix/store/5jc88y1kfkymgg469kdy1d934dnjls1m-nox-0.0.2/bin/.nox-review-wrapped", line 11, in <module>
    sys.exit(cli())
  File "/nix/store/1hxjlkv0ip5x3qxh1f6cpvrbfvx80ifw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/1hxjlkv0ip5x3qxh1f6cpvrbfvx80ifw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/nix/store/1hxjlkv0ip5x3qxh1f6cpvrbfvx80ifw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/1hxjlkv0ip5x3qxh1f6cpvrbfvx80ifw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/1hxjlkv0ip5x3qxh1f6cpvrbfvx80ifw-python3.4-click-5.1/lib/python3.4/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/1hxjlkv0ip5x3qxh1f6cpvrbfvx80ifw-python3.4-click-5.1/lib/python3.4/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/5jc88y1kfkymgg469kdy1d934dnjls1m-nox-0.0.2/lib/python3.4/site-packages/nox/review.py", line 123, in review_pr
    repo.checkout(base)
  File "/nix/store/5jc88y1kfkymgg469kdy1d934dnjls1m-nox-0.0.2/lib/python3.4/site-packages/nox/nixpkgs_repo.py", line 54, in checkout
    self.git(['checkout', '--quiet', sha])
  File "/nix/store/5jc88y1kfkymgg469kdy1d934dnjls1m-nox-0.0.2/lib/python3.4/site-packages/nox/nixpkgs_repo.py", line 48, in git
    return f(command, *args, cwd=cwd, universal_newlines=output, **kwargs)
  File "/nix/store/lwq4k9vh197mrbgzcvrd6y25yvzp3vcd-python3-3.4.3/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'checkout', '--quiet', '23772ef0a26fe631cde87690ecc586c598e2f3d9']' returned non-zero exit status 1
unibook:nixpkgs davidak$ nix-env -a
```

maybe the old git version is a problem?

**Comment by davidak** [comment]
```
unibook:~ davidak$ nix-shell -p nox --run "nox-review pr 16159"
=== Reviewing PR 16159 : Neovim darwin fixes
==> Fetching base (master)
==> Fetching PR
==> Fetching extra history for merging
==> Merging PR into base
nixos/modules/security/acme.nix: needs merge
pkgs/data/misc/geolite-legacy/default.nix: needs merge
pkgs/development/haskell-modules/configuration-lts-3.22.nix: needs merge
pkgs/development/haskell-modules/configuration-lts-4.1.nix: needs merge
pkgs/development/haskell-modules/hackage-packages.nix: needs merge
error: you need to resolve your current index first
Traceback (most recent call last):
  File "/nix/store/qfpr4v6qwpsbf0l6m43jx44bd425nw6y-nox-0.0.2/bin/.nox-review-wrapped", line 12, in <module>
    sys.exit(cli())
  File "/nix/store/7a6x00f2833pscqskj40c4jznhkxkxk4-python3.4-click-6.6/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/7a6x00f2833pscqskj40c4jznhkxkxk4-python3.4-click-6.6/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/nix/store/7a6x00f2833pscqskj40c4jznhkxkxk4-python3.4-click-6.6/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/7a6x00f2833pscqskj40c4jznhkxkxk4-python3.4-click-6.6/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/7a6x00f2833pscqskj40c4jznhkxkxk4-python3.4-click-6.6/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/7a6x00f2833pscqskj40c4jznhkxkxk4-python3.4-click-6.6/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/qfpr4v6qwpsbf0l6m43jx44bd425nw6y-nox-0.0.2/lib/python3.4/site-packages/nox/review.py", line 123, in review_pr
    repo.checkout(base)
  File "/nix/store/qfpr4v6qwpsbf0l6m43jx44bd425nw6y-nox-0.0.2/lib/python3.4/site-packages/nox/nixpkgs_repo.py", line 54, in checkout
    self.git(['checkout', '--quiet', sha])
  File "/nix/store/qfpr4v6qwpsbf0l6m43jx44bd425nw6y-nox-0.0.2/lib/python3.4/site-packages/nox/nixpkgs_repo.py", line 48, in git
    return f(command, *args, cwd=cwd, universal_newlines=output, **kwargs)
  File "/nix/store/1lslk7axs14p05lrwx5c496d08hcxd21-python3-3.4.4/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'checkout', '--quiet', '8a49ef16f19144544a76d8eee179afef88253cac']' returned non-zero exit status 1
```

**Comment by davidak** [comment]
I still have this problem and can't test PRs. :(

`nox --version` don't exists but i think it is 0.5.

```
imac:~ davidak$ rm -rf .nox/
imac:~ davidak$ time nix-shell -p nox --run "nox-review pr 22848"
...
imac:~ davidak$ cd ~/.nox/nixpkgs; git fetch
...
imac:nixpkgs davidak$ time nix-shell -p nox --run "nox-review pr 22848"
=== Reviewing PR 22848 : gpgme: fix build on macOS
==> We're in a git repo, trying to fetch it
==> Fetching base (master)
==> Fetching PR
==> Fetching extra history for merging
==> Merging PR into base
nixos/doc/manual/release-notes/rl-1703.xml: needs merge
nixos/modules/services/hardware/bluetooth.nix: needs merge
nixos/modules/services/networking/quassel.nix: needs merge
pkgs/applications/editors/emacs-modes/melpa-generated.nix: needs merge
pkgs/applications/editors/emacs-modes/melpa-stable-generated.nix: needs merge
pkgs/applications/networking/cluster/terragrunt/default.nix: needs merge
pkgs/applications/networking/cluster/terragrunt/deps.nix: needs merge
pkgs/development/haskell-modules/configuration-common.nix: needs merge
pkgs/development/haskell-modules/hackage-packages.nix: needs merge
pkgs/top-level/all-packages.nix: needs merge
error: you need to resolve your current index first
Traceback (most recent call last):
  File "/nix/store/1vasl2c260xz523x0nqgapf5zvf6b6i8-nox-0.0.5/bin/.nox-review-wrapped", line 12, in <module>
    sys.exit(cli())
  File "/nix/store/v2w3vraaqzpra8dcjg2195699bffc306-python3.5-click-6.6/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/v2w3vraaqzpra8dcjg2195699bffc306-python3.5-click-6.6/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/nix/store/v2w3vraaqzpra8dcjg2195699bffc306-python3.5-click-6.6/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/v2w3vraaqzpra8dcjg2195699bffc306-python3.5-click-6.6/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/v2w3vraaqzpra8dcjg2195699bffc306-python3.5-click-6.6/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/v2w3vraaqzpra8dcjg2195699bffc306-python3.5-click-6.6/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/1vasl2c260xz523x0nqgapf5zvf6b6i8-nox-0.0.5/lib/python3.5/site-packages/nox/review.py", line 135, in review_pr
    repo.checkout(base)
  File "/nix/store/1vasl2c260xz523x0nqgapf5zvf6b6i8-nox-0.0.5/lib/python3.5/site-packages/nox/nixpkgs_repo.py", line 54, in checkout
    self.git(['checkout', '--quiet', sha])
  File "/nix/store/1vasl2c260xz523x0nqgapf5zvf6b6i8-nox-0.0.5/lib/python3.5/site-packages/nox/nixpkgs_repo.py", line 48, in git
    return f(command, *args, cwd=cwd, universal_newlines=output, **kwargs)
  File "/nix/store/xh589g6kia35z7lz4y0maaljxw1fkq2l-python3-3.5.3/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'checkout', '--quiet', '7a113e9e83b10b8cf85ed07e10f7c47f5e5c493d']' returned non-zero exit status 1

real	1m5.482s
user	0m10.791s
sys	0m4.028s
```
