### ISSUE TITLE
git can't checkout object

### ISSUE THREAD

**Issue by davidak** [madjar/nox#43]
I'm on a branch in my fork of nixpkgs, "upstream" remote is the original.

```
[root@binary:~/nixpkgs]# nix-shell -p nox --run "nox-review wip --against upstream/master"
==> We're in a git repo, trying to fetch it
fatal: Referenz ist kein "Tree"-Objekt: 5c7131213e6529bced8a6426245a3ed968a19d3c
Traceback (most recent call last):
  File "/nix/store/hhzk3jcw27gczipv9v1jq37kz6q9q05l-nox-0.0.2/bin/.nox-review-wrapped", line 12, in <module>
    sys.exit(cli())
  File "/nix/store/qjcn2iva2j12cks59wg4a0kd2pjagb04-python3.4-click-6.2/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/qjcn2iva2j12cks59wg4a0kd2pjagb04-python3.4-click-6.2/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/nix/store/qjcn2iva2j12cks59wg4a0kd2pjagb04-python3.4-click-6.2/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/qjcn2iva2j12cks59wg4a0kd2pjagb04-python3.4-click-6.2/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/qjcn2iva2j12cks59wg4a0kd2pjagb04-python3.4-click-6.2/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/qjcn2iva2j12cks59wg4a0kd2pjagb04-python3.4-click-6.2/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/hhzk3jcw27gczipv9v1jq37kz6q9q05l-nox-0.0.2/lib/python3.4/site-packages/nox/review.py", line 83, in wip
    attrs = differences(packages_for_sha(sha),
  File "/nix/store/ahyzvs3bvcl37j3fy3ivhza1x5m0xp98-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/region.py", line 1013, in decorate
    should_cache_fn)
  File "/nix/store/ahyzvs3bvcl37j3fy3ivhza1x5m0xp98-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/region.py", line 640, in get_or_create
    async_creator) as value:
  File "/nix/store/wm9sqj1mqfaz760l0v9mxyx7k7rmqw0l-python3.4-dogpile.core-0.4.1/lib/python3.4/site-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/nix/store/wm9sqj1mqfaz760l0v9mxyx7k7rmqw0l-python3.4-dogpile.core-0.4.1/lib/python3.4/site-packages/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/nix/store/wm9sqj1mqfaz760l0v9mxyx7k7rmqw0l-python3.4-dogpile.core-0.4.1/lib/python3.4/site-packages/dogpile/core/dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "/nix/store/ahyzvs3bvcl37j3fy3ivhza1x5m0xp98-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/region.py", line 612, in gen_value
    created_value = creator()
  File "/nix/store/ahyzvs3bvcl37j3fy3ivhza1x5m0xp98-python3.4-dogpile.cache-0.5.4/lib/python3.4/site-packages/dogpile/cache/region.py", line 1009, in creator
    return fn(*arg, **kw)
  File "/nix/store/hhzk3jcw27gczipv9v1jq37kz6q9q05l-nox-0.0.2/lib/python3.4/site-packages/nox/nixpkgs_repo.py", line 89, in packages_for_sha
    repo.checkout(sha)
  File "/nix/store/hhzk3jcw27gczipv9v1jq37kz6q9q05l-nox-0.0.2/lib/python3.4/site-packages/nox/nixpkgs_repo.py", line 54, in checkout
    self.git(['checkout', '--quiet', sha])
  File "/nix/store/hhzk3jcw27gczipv9v1jq37kz6q9q05l-nox-0.0.2/lib/python3.4/site-packages/nox/nixpkgs_repo.py", line 48, in git
    return f(command, *args, cwd=cwd, universal_newlines=output, **kwargs)
  File "/nix/store/4fr5rgsizd5q72fr8lsixvb274awg6nk-python3-3.4.4/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'checkout', '--quiet', '5c7131213e6529bced8a6426245a3ed968a19d3c']' returned non-zero exit status 128
```

**Comment by domenkozar** [comment]
Could it be there was a force push in between?

**Comment by davidak** [comment]
yes, there was one.

**Comment by davidak** [comment]
i have again a similar issue:

```
nix-shell -p nox --run "nox-review pr 17680"
=== Reviewing PR 17680 : [WIP] caddy: 0.8.3 -> 0.9
==> Fetching base (master)
==> Fetching PR
==> Fetching extra history for merging
==> Merging PR into base
nixos/modules/security/acme.nix: needs merge
pkgs/data/misc/geolite-legacy/default.nix: needs merge
pkgs/development/haskell-modules/configuration-lts-3.22.nix: needs merge
pkgs/development/haskell-modules/configuration-lts-4.1.nix: needs merge
pkgs/development/haskell-modules/hackage-packages.nix: needs merge
error: you need to resolve your current index first
Traceback (most recent call last):
  File "/nix/store/qfpr4v6qwpsbf0l6m43jx44bd425nw6y-nox-0.0.2/bin/.nox-review-wrapped", line 12, in <module>
    sys.exit(cli())
  File "/nix/store/7a6x00f2833pscqskj40c4jznhkxkxk4-python3.4-click-6.6/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/7a6x00f2833pscqskj40c4jznhkxkxk4-python3.4-click-6.6/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/nix/store/7a6x00f2833pscqskj40c4jznhkxkxk4-python3.4-click-6.6/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/7a6x00f2833pscqskj40c4jznhkxkxk4-python3.4-click-6.6/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/7a6x00f2833pscqskj40c4jznhkxkxk4-python3.4-click-6.6/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/7a6x00f2833pscqskj40c4jznhkxkxk4-python3.4-click-6.6/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/qfpr4v6qwpsbf0l6m43jx44bd425nw6y-nox-0.0.2/lib/python3.4/site-packages/nox/review.py", line 123, in review_pr
    repo.checkout(base)
  File "/nix/store/qfpr4v6qwpsbf0l6m43jx44bd425nw6y-nox-0.0.2/lib/python3.4/site-packages/nox/nixpkgs_repo.py", line 54, in checkout
    self.git(['checkout', '--quiet', sha])
  File "/nix/store/qfpr4v6qwpsbf0l6m43jx44bd425nw6y-nox-0.0.2/lib/python3.4/site-packages/nox/nixpkgs_repo.py", line 48, in git
    return f(command, *args, cwd=cwd, universal_newlines=output, **kwargs)
  File "/nix/store/1lslk7axs14p05lrwx5c496d08hcxd21-python3-3.4.4/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'checkout', '--quiet', '42a71d022bfe2c09483200e7c2dfa30fec469710']' returned non-zero exit status 1
```

i force pushed again multiple times...

workaround:
```
cd /Users/davidak/.nox/nixpkgs
git reset --hard
```

@madjar maybe nox should do that every time?

**Comment by afrepues** [comment]
For me it was really hard to notice when that the issue was with `nox`'s copy of Nixpkgs, as I run it in my repo and it goes to checkout _its_ repo without any notice, and I thought the missing reference was missing in _mine_.
