### ISSUE TITLE
--keep-going does not work

### ISSUE THREAD

**Issue by lopsided98** [madjar/nox#83]
Attempting to use the `--keep-going` option results in this error:
```
Traceback (most recent call last):
  File "/nix/store/7ain03ansrvym25chk1pzd5zgq4lk2qm-nox-0.0.6/bin/.nox-review-wrapped", line 12, in <module>
    sys.exit(cli())
  File "/nix/store/fgglv66s6j0x44ivvzad5mrr0bw3ajb4-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/fgglv66s6j0x44ivvzad5mrr0bw3ajb4-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/nix/store/fgglv66s6j0x44ivvzad5mrr0bw3ajb4-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/fgglv66s6j0x44ivvzad5mrr0bw3ajb4-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/fgglv66s6j0x44ivvzad5mrr0bw3ajb4-python3.6-click-6.7/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/fgglv66s6j0x44ivvzad5mrr0bw3ajb4-python3.6-click-6.7/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/nix/store/7ain03ansrvym25chk1pzd5zgq4lk2qm-nox-0.0.6/lib/python3.6/site-packages/nox/review.py", line 71, in _
    f(*args, **kwargs)
  File "/nix/store/7ain03ansrvym25chk1pzd5zgq4lk2qm-nox-0.0.6/lib/python3.6/site-packages/nox/review.py", line 109, in wip
    build_in_path(ctx.obj['extra-args'], attrs, '.', dry_run=ctx.obj['dry_run'])
  File "/nix/store/7ain03ansrvym25chk1pzd5zgq4lk2qm-nox-0.0.6/lib/python3.6/site-packages/nox/review.py", line 38, in build_in_path
    click.echo('Invoking {}'.format(' '.join(command)))
TypeError: sequence item 1: expected str instance, list found
```

I have not tested this fix, but it looks like the problem is caused by a trivial issue on [review.py line 83](https://github.com/madjar/nox/blob/master/nox/review.py#L83), where `"--keep-going"` is wrapped in a list when it should not be.

**Comment by dezgeg** [comment]
Yup. https://github.com/madjar/nox/pull/86

**Comment by das-g** [comment]
It looks like this is fixed in `master`, but not yet in any release. Can we please get a release with the fix?
