### ISSUE TITLE
KeyError: 'meta' after a recent unstable update

### ISSUE THREAD

**Issue by jktjkt** [madjar/nox#97]
```console-session
$ nox nox
Traceback (most recent call last):
  File "/nix/store/gqjvrvh1n8b1nz4kdqslqhfvds0j5imk-nox-0.0.6/bin/.nox-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/mkkjjf0qp8xspkddn7r144pkdzldvyqj-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/mkkjjf0qp8xspkddn7r144pkdzldvyqj-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/nix/store/mkkjjf0qp8xspkddn7r144pkdzldvyqj-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/mkkjjf0qp8xspkddn7r144pkdzldvyqj-python3.8-click-7.1.2/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/nix/store/gqjvrvh1n8b1nz4kdqslqhfvds0j5imk-nox-0.0.6/lib/python3.8/site-packages/nox/search.py", line 64, in main
    results = [p for p in all_packages(force_refresh)
  File "/nix/store/gqjvrvh1n8b1nz4kdqslqhfvds0j5imk-nox-0.0.6/lib/python3.8/site-packages/nox/search.py", line 64, in <listcomp>
    results = [p for p in all_packages(force_refresh)
  File "/nix/store/gqjvrvh1n8b1nz4kdqslqhfvds0j5imk-nox-0.0.6/lib/python3.8/site-packages/nox/search.py", line 52, in <genexpr>
    return (Package(attr, v['name'], v['meta'].get('description', ''))
KeyError: 'meta'
```
System info:
```console-session
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.16.7, NixOS, 22.05 (Quokka)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.0`
 - channels(root): `"nixos-22.05pre353535.48d63e924a2"`
 - channels(jkt): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by madjar** [comment]
Arf, I'm guessing that there's now some package that doesn't have a `meta`.

Do you mind if I pull your commit?

**Comment by jktjkt** [comment]
Oops, I must have missed your reply. Yes please, feel free to merge that commit. I have not submitted a PR because the build instructions wouldn't work for me out-of-box on unstable, so I couldn't test properly (and I am basically a Nix neophyte).

**Comment by madjar** [comment]
Merged! Thanks a lot!

Ans thanks for mentioning the build instructions are not working. I'll have to take a look at that :)
